
:www:
  :host: 0.0.0.0
  :port: 8000
  :backends:
    - :host: 127.0.0.1
      :port: 3000
    - :host: 127.0.0.1
      :port: 3001
:api:
  :host: 0.0.0.0
  :port: 8001
  :backends:
    - :host: 127.0.0.1
      :port: 3000
    - :host: 127.0.0.1
      :port: 3001
